### ISSUE TITLE
Docker tab, setup flow - 3h

### ISSUE THREAD

**Issue by m-esm** [shellops/shellops-panel#1]
Angular component to introduce docker and start to install flow

**Comment by matthias1999** [comment]
Estimate (hours): 4
Uncertainty factor: 2

**Comment by m-esm** [comment]
Estimate (hours): 2
Uncertainty factor: 2

**Comment by m-esm** [comment]
CTOP containers table
![image](https://user-images.githubusercontent.com/16524171/105576432-0245db00-5d88-11eb-92a6-6b78c75a5df6.png)

**Comment by m-esm** [comment]
![image](https://user-images.githubusercontent.com/16524171/105576501-581a8300-5d88-11eb-9032-3c6d8bc093bf.png)
